### ISSUE TITLE
/slowllama/logs/prepare_model.log doesnt exist

### ISSUE THREAD

**Issue by miladf2** [okuvshynov/slowllama#12]
Hi, when I try to run the prepare_model.py which is the first script I get 
/slowllama/logs/prepare_model.log
does not exist. I cant find that log file anywhere.

**Comment by okuvshynov** [comment]
let me double-check, thanks for reporting

**Comment by okuvshynov** [comment]
logs folder didn't exist. I added it, so you can either pull updates, or just create empty directory yourself.

**Comment by okuvshynov** [comment]
This should be resolved
