### ISSUE TITLE
run prepare_model.py error

### ISSUE THREAD

**Issue by Barryzhang1** [okuvshynov/slowllama#14]
when I use CodeLlama-7b to run  prepare_model.py,An exception occurred

**_RuntimeError: The expanded size of the tensor (32000) must match the existing size (32016) at non-singleton dimension 0.  Target sizes: [32000, 4096].  Tensor sizes: [32016, 4096]_**

**Comment by okuvshynov** [comment]
This is regular CodeLLama-7b, downloaded from https://llama.meta.com/llama-downloads/ ?

**Comment by Barryzhang1** [comment]
Yes, that's right

**Comment by Barryzhang1** [comment]
I think I found the reason,I download wrong model

**Comment by okuvshynov** [comment]
Hi, sorry for delay, did you figure it out? May be related to https://github.com/okuvshynov/slowllama/issues/16 ?

**Comment by Barryzhang1** [comment]
thank you much for your reply,I changed the model and the problem was solved.
I used CodeLlama-7b before,and when I use CodeLlama-7b-python,this error was gone
